language: go
before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- dep ensure
- sudo apt-get install libpcap-dev
script:
- sudo -E bash -c "go test ./..."

notifications:
  email: false